### ISSUE TITLE
CryptoAnalysis on Maven Central or our build server repository

### ISSUE THREAD

**Issue by linghuiluo** [CROSSINGTUD/CryptoAnalysis#101]
@kruegers @johspaeth 
What do you think of putting CryptoAnalysis on Maven Central or on https://soot-build.cs.uni-paderborn.de/nexus/#browse/browse/components:soot-snapshot?

**Comment by johspaeth** [comment]
Yes, that is a good idea. We should do that.

**Comment by linghuiluo** [comment]
Great! tell me when it is done.

**Comment by kruegers** [comment]
Hey @linghuiluo,
It's available here: https://soot-build.cs.uni-paderborn.de/nexus/#browse/browse/components:soot-snapshot:36e3dec8de528c9bf076cc990871dc50

**Comment by johspaeth** [comment]
Cool, thanks. I guess you manually uploaded it? We should automatically deployed it by shippable/Jenkins?

**Comment by linghuiluo** [comment]
@kruegers  perfect! just tried it out.

**Comment by kruegers** [comment]
Yes and no. I extended the POM to deploy it to the Nexus during the deploy phase*. All we would need to do now is to give shippable/Jenkins the credentials (and, potentially, select the correct phase in the shippable script).

* I haven't pushed it yet because I'm currently doing something else in the master branch. Will push it once this is done.
