### ISSUE TITLE
Reorganize CrySL Architecture

### ISSUE THREAD

**Issue by AnakinRaW** [CROSSINGTUD/CryptoAnalysis#200]
As discussed in today's meeting: 

- [x] Perform a relabeling fro CrypSL to CrySL java source files
- [ ] Extract and move (where possible) CrySL specific code to [CrySL Repo](https://github.com/CROSSINGTUD/CryptSL) (e.g.: such as CrySLRulesetSelector, etc.)
- [ ] Move relevant constants/enums (like the CrySL source file ending) into a separate file 

In edit for my suggestion about to referencing CrySL in this Repo: I didn't look carefully enough what exactly was referenced. I was under the assumption that this repo depends on the [Ruleset Repo](https://github.com/CROSSINGTUD/Crypto-API-Rules). As this obviously is not the case my comment becomes obsolete. Depending on the [CrySL Engine](https://github.com/CROSSINGTUD/CryptSL) of course makes sense. I'd still agree however to minimize the referenced code basis by splitting the CrySL-Repo into more independent projects

**Comment by smeyer198** [comment]
Since this issue may become relevant in the future, the CrySL specific code concerns all classes in the packages [crypto.rules](https://github.com/CROSSINGTUD/CryptoAnalysis/tree/develop/CryptoAnalysis/src/main/java/crypto/rules) and [crypto.cryslhandler](https://github.com/CROSSINGTUD/CryptoAnalysis/tree/develop/CryptoAnalysis/src/main/java/crypto/cryslhandler). In total, reading the rules is **not** part of the actual analysis. Instead, the analysis takes a `Collection` of [CrySLRule](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/develop/CryptoAnalysis/src/main/java/crypto/rules/CrySLRule.java) as input and runs the analysis with them. One can obtain a collection using the [RulesetReader](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/develop/CryptoAnalysis/src/main/java/crypto/cryslhandler/RulesetReader.java). Therefore, the following new tasks arise:
- [ ] Move the `crypto.rules` and `crypto.cryslhandler` into the CrySL Repository (probably into a new submodule)
- [ ] Remove not needed dependencies from this repository (mainly XText)
- [ ] Document in CrySL Repository how to use the `RulesetReader` and obtain the Ruleset from a directory or Zip file
