### ISSUE TITLE
Sarif Reporter prints wrong version number

### ISSUE THREAD

**Issue by AnakinSklavenwalker** [CROSSINGTUD/CryptoAnalysis#307]
Class `SARIFHelper` currently has hardcoded version details about the current version of CryptoAnalysis. 

We need to change this, so it always reports the correct, current version of the tool.

**Comment by enriozuni** [comment]
After a discussion with @AnakinSklavenwalker, we got to the conclusion that CryptoAnalysis is actually reporting the CogniCrypt version as shown in the lines in both the [SARIFHelper](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/develop/CryptoAnalysis/src/main/java/crypto/reporting/SARIFHelper.java#L55) and [SARIFConfig](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/develop/CryptoAnalysis/src/main/java/crypto/reporting/SARIFConfig.java#L15) files, and not that of CryptoAnalysis as it was previously believed. Since this is not needed, it should be omitted from the SARIF reporting.

Furthermore, the version number of CryptoAnalysis is missing and it should be added to the SARIF reporter. The version must be loaded dynamically and not hardcoded. A simple way of doing this is to load it from the [POM](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/develop/CryptoAnalysis/pom.xml#L7) file in CryptoAnalysis.

Lastly, another addition would be to include the dynamically loaded version of CryptoAnalysis in other reporting formats like TXT and CSV, besides that of SARIF.
