### ISSUE TITLE
Input args seem to fail for relative paths

### ISSUE THREAD

**Issue by AnakinSklavenwalker** [CROSSINGTUD/CryptoAnalysis#330]
```
.../desktop$ java -cp CryptoAnalysis-2.8.0-SNAPSHOT-jar-with-dependencies.jar crypto.HeadlessCryptoScanner --rulesDir=./JavaCryptographicArchitecture --applicationCp=./someApp.jar
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at crypto.HeadlessCryptoScanner.createFromOptions(HeadlessCryptoScanner.java:109)
        at crypto.HeadlessCryptoScanner.main(HeadlessCryptoScanner.java:82)

.../desktop$ ls
d-----                 JavaCryptographicArchitecture
-a----                  CryptoAnalysis-Android-2.8.0-SNAPSHOT-jar-with-dependencies.jar
-a----                  someApp.jar

```

Apparently the current versions (2.7.1, 2.7.2 and 2.8.0-Snapshot) relative paths for `--rulesDir` and/or `--applicationCp` seems to fail, as shown in the stacktrace.

**Comment by enriozuni** [comment]
I know why the error is happening. It is related to this PR #288 where I had implemented our own parser for parsing the CLI arguments which are not anymore dependent on the `Apache Commons CLI` dependency. I just saw that the PR was merged 5 days ago into develop branch by @AnakinSklavenwalker.

The main changes to the parser include the one where we don't anymore need to give the arguments in the form of `--applicationCp=<absolute-application-path>`  but rather `--applicationCp  <absolute-application-path>`, where I have gotten rid of the redundant `=` sign in between the key and value pairs. This way we can put as many spaces in between them and makes it faster to write. Also, many CLI tools like Maven, Docker, etc, use the same interface for typing the arguments so I thought to incorporate the same one.

Sorry for not being so explicit in my PR. If you want, I can update the README file of the CryptoAnalysis repository since I know in detail how the parser works. Or, if you want, I can change the parser so it parses the arguments as it did before. Although IMO works and looks better like this :)
