### ISSUE TITLE
Include CogniCryptExample-Project and run static analysis in headless mode

### ISSUE THREAD

**Issue by johspaeth** [CROSSINGTUD/CryptoAnalysis#52]
- [x] Get the template code from [here](https://github.com/CROSSINGTUD/CogniCrypt-ExampleProjects)
- [x] Use CogniCrypt to generate code into the projects.
- [x] Specify how many error markes you expect on the project (hopefully none) in an additional [HeadlessTest](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/master/CryptoAnalysis/src/test/java/test/headless/HeadlessTests.java)

**Comment by enriozuni** [comment]
I have downloaded the template code which contains four Example Projects named: FileEncryptor, LongTermArchiver, SecureFileTransmitter, and UserAuthenticator. All these projects contained just some skeleton code to start with.

I used the CogniCrypt plugin on Eclipse to generate code into these projects and realize each projects' respective goal. For example, in the FileEncryptor project, I used CogniCrypt and selected the task of "Encrypt Data Using a Secret Key" to generate code into it, and did the same procedure in each project with their respective CogniCrypt task. After all the projects run successfully, fortunately none of them generated any reports or errors. 

Since none of them introduced errors with the code generated by CogniCrypt, there was no need to specify any errors that were expected for each project in HeadlessTest.java. Anyway, I just left the test skeleton code into HeadlessTest.java for each project, should they introduce any errors in the future with the code generated from CogniCrypt.
