### ISSUE TITLE
Handling of reversal operations in CrySL and CogniCrypt(_SAST)

### ISSUE THREAD

**Issue by kruegers** [CROSSINGTUD/CryptoAnalysis#80]
This issue is a follow-up issue to the discussions in #70. It is meant to facilitate a proper discussion of the problem. Please refer to the discussion there for the original jumping-off example.

The general issue is as follows:
When using PBEKeySpec (either for password hashing or password-based encryption), we require a [random salt](https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/master/src/de/darmstadt/tu/crossing/PBEKeySpec.cryptsl#L23) to be used. That is good and all, but when the operation is reversed (e.g. decryption in case of PBE or comparing a hash with an exisiting one), the salt obviously is already there. It may come with the ciphertext or hash comparee or is stored in a database or file. Point is, it is not random and can never be random because it is not generated anew. At the moment, this causes CogniCrypt_SAST to report an error for these kinds of decryption (and hash comparison) where none should be reported. As discussed in #70, IVs have similar issues. 

The question now is how to handle those in a systematic manner. //cc @ericbodden, @karimhamdanali, @akwick, @miramezini, @mreif

**Comment by kruegers** [comment]
In a discussion @johspaeth and I had yesterday, he suggested to offer quickfixes that would allow the user to tell CogniCrypt the data comes from a secure external source. CogniCrypt would then generate a source code annotation telling the analysis to assume the predicate to be there.

**Comment by ericbodden** [comment]
Can we not somehow conditionalize the _random_-requirement on the Chipher's MODE? For ENCRYPT_MODE we do require the random-predicate, for DECRYPT_MODE we do not. There, instead we should ideally require some sort of _loaded_ predicate that ensures that the salt is derived from a stream input and not retrieved from a constant.

**Comment by ericbodden** [comment]
@kruegers can you provide a concrete example? The one in #70 should work with the current formulation in Cipher, does it not? What is a concrete example where this fails?

**Comment by kruegers** [comment]
Sure. Johannes pointed to [this](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/32c79e6c6f8d0ee48e8de6b046571d932bae5a7f/CryptoAnalysisTargets/OracleExample/src/Crypto/PWHasher.java#L30) example in the other thread.

	public Boolean verifyPWHash(char[] pwd, String pwdhash) throws GeneralSecurityException {
		String[] parts = pwdhash.split(":");
		byte[] salt = fromBase64(parts[0]);

		PBEKeySpec spec = new PBEKeySpec(pwd, salt, 65536, 224);
		SecretKeyFactory f = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA224");
		Boolean areEqual = slowEquals(f.generateSecret(spec).getEncoded(), fromBase64(parts[1]));
		spec.clearPassword();
		return areEqual;
	}

In the method verifyPWHash, an error marker would be generated for the salt in line 30. Since the method verifies an existing hash, the salt used for the generation of that hash is being reused here.  However, since the constructor call to PBEKeySpec is exactly the same as in createPWHash(), one cannot distinguish between the two calls directly.

**Comment by kruegers** [comment]
We implement Johannes' idea from above:
The user can select a quickfix saying something along the lines of "This object comes from a stream/database/other external source and is actually secure." When chosen, CogniCrypt will generate a source-code annotation and a 'load' predicate for the object. This predicate serves as a substitute for the actual predicate. We can decide at a later point whether CogniCrypt should still generate a warning in this case or nothing at all.

**Comment by AndreSonntag** [comment]
„The user can select a quickfix saying something along the lines of "This object comes from a stream/database/other external source and is actually secure." When chosen, CogniCrypt will generate a source-code annotation and a 'load' predicate for the object.“

**Intermediate status:**
Idea: add an annotation at the problem marker position
Problem: mostly, the problem marker position is a method call and it is not possible to add annotations on method calls.
Solution: add an annotation on the allocation side of the problem variable

After I am done with this solution on the _CogniCrypt side_, my new task was the annotation processing on the _CryptoAnalysis side_. Unfortunately, I have figured out that annotations on local variables are not stored persistently in Java bytecode. Due to this problem the local variable annotations are not in the Jimple code and the CryptoAnalysis is not able to find the annotations. Also Soot doesn’t support local variable annotations. [[1](https://mailman.cs.mcgill.ca/pipermail/soot-list/2012-February/004094.html)]

The only solution I see is to generate the annotations directly to the method head.

**Comment by ericbodden** [comment]
Hmm good point. I had forgotten about this... I wonder: are type annotations stored in the bytecode? Maybe we could somehow make use of those.

**Comment by AndreSonntag** [comment]
**Update**
After consultation with Stefan, the new solution is to insert the following call "CC.ensuresPredicate(predicate, variable)" instead of annotations. Currently the solution looks like in the following pictures. 

Case 1: required predicate error in method body
![image](https://user-images.githubusercontent.com/31883471/52063261-8f2b7480-2572-11e9-98b4-e527fc9fa3aa.png)

Case 2: required predicate error in class variables
![image](https://user-images.githubusercontent.com/31883471/52063282-99e60980-2572-11e9-8b3c-8ea168e0c15a.png)

Case 2 is relative unsightly. After the complete workflow is implemented, I try to convert the Jimple variable name into the source code variable name.
